language: python

sudo: required
dist: trusty

python:
  - 2.7

services:
  - docker

install:
  - git clone https://github.com/getavalon/core.git
  - docker run --name mindbender-mongo -d mongo
  - docker build -t pyblish/mindbender -f Dockerfile-maya2016 .

script:
  - >
    PYTHONPATH=$(pwd)/core 
    docker run
    --rm
    -v $(pwd):/workspace
    --link mindbender-mongo:mongo
    -e COVERALLS_REPO_TOKEN
    -e TRAVIS_JOB_ID
    -e MINDBENDER_MONGO=mongodb://mongo:27017
    pyblish/mindbender
