application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
label = "Autodesk Maya 2016x64"
ftrack_label = "Maya"
schema = "avalon-core:application-1.0"
executable = "maya2016"
description = ""
icon ="maya_icon"
ftrack_icon = '{}/app_icons/maya.png'

[copy]
"{PYPE_MODULE_ROOT}/pype/resources/maya/workspace.mel" = "workspace.mel"

[environment]
MAYA_DISABLE_CLIC_IPM = "Yes"  # Disable the AdSSO process
MAYA_DISABLE_CIP = "Yes"  # Shorten time to boot
MAYA_DISABLE_CER = "Yes"
PYTHONPATH = [
	"{AVALON_CORE}/setup/maya",
	"{PYTHONPATH}"
]
