blank_issues_enabled: false
contact_links:
  - name: Ynput Community Discussions
    url: https://community.ynput.io
    about: Please ask and answer questions here.
  - name: Ynput Discord Server
    url: https://discord.gg/ynput
    about: For community quick chats.