executable = "nukestudio10.0"
schema = "avalon-core:application-1.0"
application_dir = "nukestudio"
label = "NukeStudio"
label_variant = "10.0"
ftrack_label = "NukeStudio"
icon = "app_icons/nuke.png"
ftrack_icon = '{}/app_icons/nuke.png'
