name: â³ Nightly Prerelease

on:
  workflow_dispatch:


jobs:
  create_nightly:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸš› Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python requirements
      run: pip install gitpython semver PyGithub

    - name: ðŸ”Ž Determine next version type
      id: version_type
      run: |
        TYPE=$(python ./tools/ci_tools.py --bump --github_token ${{ secrets.YNPUT_BOT_TOKEN }})
        echo "type=${TYPE}" >> $GITHUB_OUTPUT

    - name: ðŸ’‰ Inject new version into files
      id: version
      if: steps.version_type.outputs.type != 'skip'
      run: |
        NEW_VERSION_TAG=$(python ./tools/ci_tools.py --nightly --github_token ${{ secrets.YNPUT_BOT_TOKEN }})
        echo "next_tag=${NEW_VERSION_TAG}" >> $GITHUB_OUTPUT

    - name: ðŸ’¾ Commit and Tag
      id: git_commit
      if: steps.version_type.outputs.type != 'skip'
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git checkout main
        git pull
        git add .
        git commit -m "[Automated] Bump version"
        tag_name="CI/${{ steps.version.outputs.next_tag }}"
        echo $tag_name
        git tag -a $tag_name -m "nightly build"

    - name: Push to protected main branch
      uses: CasperWA/push-protected@v2.10.0
      with:
        token: ${{ secrets.YNPUT_BOT_TOKEN }}
        branch: main
        tags: true
        unprotect_reviews: true

    - name: ðŸ”¨ Merge main back to develop
      uses: everlytic/branch-merge@1.1.0
      if: steps.version_type.outputs.type != 'skip'
      with:
        github_token: ${{ secrets.YNPUT_BOT_TOKEN }}
        source_ref: 'main'
        target_branch: 'develop'
        commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'

    - name: Invoke Update bug report workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: update_bug_report.yml
        token: ${{ secrets.YNPUT_BOT_TOKEN }}