name: Nightly Prerelease

on:
  workflow_dispatch:


jobs:
  create_nightly:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸš› Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python requirements
      run: pip install gitpython semver PyGithub

    - name: ğŸ” Determine next version type
      id: version_type
      run: |
        TYPE=$(python ./tools/ci_tools.py --bump --github_token ${{ secrets.GITHUB_TOKEN }})

        echo ::set-output name=type::$TYPE

    - name: ğŸ’‰ Inject new version into files
      id: version
      if: steps.version_type.outputs.type != 'skip'
      run: |
        RESULT=$(python ./tools/ci_tools.py --nightly --github_token ${{ secrets.GITHUB_TOKEN }})

        echo ::set-output name=next_tag::$RESULT

    - name: "âœï¸ Generate full changelog"
      if: steps.version_type.outputs.type != 'skip'
      id: generate-full-changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.2
      with:
        token: ${{ secrets.ADMIN_TOKEN }}
        addSections: '{"documentation":{"prefix":"### ğŸ“– Documentation","labels":["type: documentation"]},"tests":{"prefix":"### âœ… Testing","labels":["tests"]},"feature":{"prefix":"**ğŸ†• New features**", "labels":["type: feature"]},"breaking":{"prefix":"**ğŸ’¥ Breaking**", "labels":["breaking"]},"enhancements":{"prefix":"**ğŸš€ Enhancements**", "labels":["type: enhancement"]},"bugs":{"prefix":"**ğŸ› Bug fixes**", "labels":["type: bug"]},"deprecated":{"prefix":"**âš ï¸ Deprecations**", "labels":["depreciated"]}, "refactor":{"prefix":"**ğŸ”€ Refactored code**", "labels":["refactor"]}}'
        issues: false
        issuesWoLabels: false
        sinceTag: "3.0.0"
        maxIssues: 100
        pullRequests: true
        prWoLabels: false
        author: false
        unreleased: true
        compareLink: true
        stripGeneratorNotice: true
        verbose: true
        unreleasedLabel: ${{ steps.version.outputs.next_tag }}
        excludeTagsRegex: "CI/.+"
        releaseBranch: "main"

    - name: "ğŸ–¨ï¸ Print changelog to console"
      if: steps.version_type.outputs.type != 'skip'
      run: cat CHANGELOG.md

    - name: ğŸ’¾ Commit and Tag
      id: git_commit
      if: steps.version_type.outputs.type != 'skip'
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "[Automated] Bump version"
        tag_name="CI/${{ steps.version.outputs.next_tag }}"
        echo $tag_name
        git tag -a $tag_name -m "nightly build"

    - name: Push to protected main branch
      uses: CasperWA/push-protected@v2.10.0
      with:
        token: ${{ secrets.ADMIN_TOKEN }}
        branch: main
        tags: true
        unprotect_reviews: true

    - name: ğŸ”¨ Merge main back to develop    
      uses: everlytic/branch-merge@1.1.0
      if: steps.version_type.outputs.type != 'skip'
      with:
        github_token: ${{ secrets.ADMIN_TOKEN }}
        source_ref: 'main'
        target_branch: 'develop'
        commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'